stages:
  - test

before_script:
  - asdf install
  - pnpm install

test:
  script:
    - pnpm typecheck
    - pnpm build
  except:
    - vite-vue3-boilerplate
    - develop
    - staging
    - master
