stages:
  - test
  # - deploy

before_script:
  - asdf install
  - pnpm install

test:
  script:
    - pnpm run lint
    - pnpm run lint:ts
  except:
    - vite-vue3-boilerplate
    - develop
    - staging
    - master

# deploy_staging:
#   stage: deploy
#   script:
#     - pnpm staging
#     - pnpm deploy:staging
#   only:
#     - staging
#   tags:
#     - nuc-runner

# deploy_production:
#   stage: deploy
#   script:
#     - pnpm build
#     - pnpm deploy:production
#   only:
#     - master
#   tags:
#     - nuc-runner
